# Generated by Django 5.2.16 on 2026-07-31 12:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('team', 'Team')], db_index=True, default='team', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pitches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PitchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('item_status', models.CharField(choices=[('sent', 'Sent'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed')], db_index=True, default='sent', max_length=20)),
                ('reject_reason_code', models.CharField(blank=True, choices=[('already_used', 'Already used'), ('casino_links', 'Casino links'), ('weak_site', 'Weak site'), ('mfa', 'MFA (Made for advertising)'), ('bad_niche', 'Bad niche fit'), ('price_high', 'Price too high'), ('low_metrics', 'Low traffic / metrics'), ('other', 'Other')], max_length=40)),
                ('reject_comment', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True)),
                ('live_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pitch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pitch_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('niche', models.CharField(blank=True, db_index=True, max_length=255)),
                ('countries', models.CharField(blank=True, help_text='Comma-separated country codes/names', max_length=500)),
                ('region_focus', models.CharField(blank=True, max_length=255)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('min_dr', models.PositiveIntegerField(blank=True, null=True)),
                ('min_da', models.PositiveIntegerField(blank=True, null=True)),
                ('min_traffic', models.PositiveIntegerField(blank=True, null=True)),
                ('avoid_notes', models.TextField(blank=True, help_text='e.g. MFA, casino links, adult')),
                ('workflow_notes', models.TextField(blank=True)),
                ('requirements_brief', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_members', models.ManyToManyField(blank=True, limit_choices_to={'role': 'team'}, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pitch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='core.project'),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('url', models.URLField(blank=True)),
                ('region', models.CharField(blank=True, choices=[('europe', 'Europe'), ('north_america', 'North America'), ('english', 'English'), ('other', 'Other')], db_index=True, max_length=32)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('niche', models.CharField(blank=True, db_index=True, max_length=255)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('dr', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('da', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('traffic', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('backlink_price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True)),
                ('banner_price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('negotiating', 'Negotiating'), ('agreed', 'Agreed'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed'), ('blocked', 'Blocked')], db_index=True, default='draft', max_length=20)),
                ('publisher_email', models.EmailField(blank=True, max_length=254)),
                ('outreach_notes', models.TextField(blank=True)),
                ('warning_flags', models.CharField(blank=True, help_text='Global caution tags e.g. MFA, weak, casino', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sites', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sites', to=settings.AUTH_USER_MODEL)),
                ('primary_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_sites', to='core.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishedPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pitch_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_placement', to='core.pitchitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_placements', to='core.project')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_placements', to='core.site')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddField(
            model_name='pitchitem',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_items', to='core.site'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['status', 'country'], name='core_site_status_e69a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['status', 'niche'], name='core_site_status_f9751d_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['assigned_to', 'status'], name='core_site_assigne_2b2248_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedplacement',
            index=models.Index(fields=['project', 'site'], name='core_publis_project_a0de5e_idx'),
        ),
        migrations.AddIndex(
            model_name='pitchitem',
            index=models.Index(fields=['item_status', 'reject_reason_code'], name='core_pitchi_item_st_91afd7_idx'),
        ),
        migrations.AddIndex(
            model_name='pitchitem',
            index=models.Index(fields=['site', 'item_status'], name='core_pitchi_site_id_349af8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pitchitem',
            unique_together={('pitch', 'site')},
        ),
    ]
